### PR TITLE
Method-To-Return-ImagePlus-Of-VolumeRenderedImage

### PR DESCRIPTION
**Pull request by hansenjn**
I have inserted two methods that allow to use VolumeViewer in custom-written ImageJ plugins to obtain a 3D Visualization for a given image under given preferences.

This will facilitate to use VolumeViewer in custom-written ImageJ plugins as a method to automatically generate 3D visualizations.

### CODE REVIEW

**Comment by ctrueden** [comment]
@kaibarthel Thoughts or opinions about this? Do you like it? Generally speaking: do you have any interest in being actively involved in this repository?

**Comment by kaibarthel** [comment]
I think this is a good idea. Thank you.
I do not have too much time very to work on this project, but I would like be involved in this repository.

**Comment by ctrueden** [comment]
> I think this is a good idea.

@kaibarthel Great! So then I merge it.

> I would like be involved in this repository.

I double checked, and you are already admin+maintainer of this repository. It would be helpful if you could clarify the project roles you see yourself filling—see [here](https://imagej.net/Team) for a list. Currently you [are listed](https://github.com/fiji/Volume_Viewer/blob/0d7bcc7975327e25af6e833793ed74b289cff2f9/pom.xml#L34-L44) as: `founder`, `lead`, `developer`, `debugger`, `reviewer`, `support`. But potentially we should remove the `developer` role, since that would communicate that you do not have time to field any feature requests from the community. Leaving `debugger` means you would still make a best effort to fix bugs as time allows. Leaving `reviewer` means you try to pay attention to PRs here; leaving `support` means you respond to issues and posts on the forum. Soon, every component's wiki page (in this case: https://imagej.net/Volume_Viewer) will be auto-updated to match the information in its `pom.xml` file, so that's another reason it is important to get this metadata right. What do you think?

**Comment by ctrueden** [comment]
Thanks @hansenjn for the contribution!

**Pull request merged**
